
**Von:** Daniel Körsten

**Gruppe:** 34

== Was habe ich gelernt?
* Planung und Programmierung eines Projekts von Anfang an
* Gemeinsame Arbeit an einem Projekt und deren Bedeutung. Sprich, wie wichtig die Absprache ist und, dass man sich auf seine "Kollegen" verlassen muss, denn alleine klappt es nicht.
* Theorie aus dem Studium einmal praktisch anzuwenden
* Arbeit mit JavaDocs oder allgmein Einlesen in Dokumentationen

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
* Organisation und Kommunikation ist das A&O
* Man konnte sich mit den Anderen über Probleme und deren Lösung austauschen, wenn man vor einem ähnlichen Problem steht
* Gruppenmitglieder haben auch Ideen, an die man selbst nicht gedacht hat
* Leider war auf ein Teammitglied nicht immer 100% Verlass bzw. auch nicht die nötige Motivation da, was hin und wieder zu Problemen oder Verständigungsschwierigkeiten geführt hat.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
* Den Einstieg empfand ich als sehr schwer. Es ist viel Arbeit sich einzuarbeiten.
* Die Dokumentation ist nicht Lückenlos. Man fühlt sich manchmal einfach ins Wasser geschmissen.
* Der Videoshop enthält einen Fehler bezgl. Eingabedatenvalidierung. Die Lösung des Problems hat micht viel Zeit gekostet (Siehe PullRequest für Videoshop (von @technikamateur), der das fixt, aber immer noch nicht angenommen ist.)
* Spring/SalesPoint sind ein sehr mächtiges Werkzeug. Vielleicht sollte man nicht direkt mit solchen großen Frameworks arbeiten, wenn man noch nie vorher etwas mit Frameworks zu tun hatte.
* SalesPoint an sich ist sehr hilfreich, wenn man einmal die Idee dahinter verstanden hat und mit der Dokumentation umgehen kann.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
* Habe ich glaube in den anderen Punkten größtenteils zum Ausdruck gebracht.
* Ich würde mir mehr Zeit wünschen. Es ist doch sehr viel Zeit, die in das Projekt fließt. Sicherlich kann man das aber nur schwer ändern.
* Im Lernraum gerne mehr Tutoren einsetzten. Teilweise musste ich für die Klärung einer kleinen Frage 1 Stunde warten.
* SonarQube bitte UNBEDINGT für den develop freischalten

== Feedback für den Tutor
Daniel konnte uns bei unseren Problemen immer helfen. Er hat auf E-Mails zügig reagiert. Ich habe mich von ihm gut betreut gefühlt. Er hat uns immer den Weg gezeigt und uns geholfen, unsere Prioritäten zu setzten.

== Sonstiges und Anmerkungen
