= Zeiterfassung für Gruppe XX

=== Aktuelle Zeiterfassung: link:https://docs.google.com/spreadsheets/d/1nr8pW949Duenh1e8whPZbrdYzpz3W-HcMXC3Jbl9jX8[Google Sheet]

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Daniel G |Daniel K |Johannes |Leo |Ricco |Meeting
|1  |120 |120    |90    |240   |270    |120
|2  |360   |420    |180    |540    |240    |540    
|3  |750   |660    |720    |540    |490    |300    
|4  |430  |300    |720    |420    |810    |270    
|5  |520   |660    |600    |810    |540    |390    
|6  |830   |630    |960    |1080    |420    |160    
|7  |1200   |690    |660    |750    |435    |90    
|8  |760   |1050    |960   |570    |650    |90    
|9  |810  |1410    |1200    |1380    |1275    |180   
|10 |650   |660    |480    |180    |870    |90    
|11 |220   |…    |600    |…    |…    |…    
|12  |1600   |…    |1200    |…    |…    |…    
|Gesamt |8250 |   |8370   |   |   |
|Pro Woche |688 |   |910   |   |   |
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
