= Zeiterfassung für Gruppe XX

=== Aktuelle Zeiterfassung: link:https://docs.google.com/spreadsheets/d/1nr8pW949Duenh1e8whPZbrdYzpz3W-HcMXC3Jbl9jX8[Google Sheet]

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Daniel G |Daniel K |Johannes |Leo |Ricco |Meeting
|1  |120 |120    |90    |240   |270    |120
|2  |360   |420    |180    |540    |240    |540    
|3  |750   |660    |720    |540    |490    |300    
|4  |…   |300    |…    |…    |810    |270    
|5  |…   |…    |…    |…    |…    |…    
|6  |…   |…    |…    |…    |…    |…    
|7  |…   |…    |…    |…    |…    |…    
|8  |…   |…    |…    |…    |…    |…    
|9  |…   |…    |…    |…    |…    |…    
|10  |…   |…    |…    |…    |…    |…    
|11  |…   |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
